import { useState } from 'react'
import { useInvoices } from '../hooks/useInvoices'
import type { Invoice } from '../api/invoices'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell,
  PieChart, Pie, Legend,
} from 'recharts'
import { format, startOfWeek, endOfWeek, subWeeks } from 'date-fns'

function groupByWeek(invoices: Invoice[]) {
  const weeks: { week: string; amount: number; count: number }[] = []
  for (let i = 5; i >= 0; i--) {
    const start = startOfWeek(subWeeks(new Date(), i))
    const end = endOfWeek(start)
    const paid = invoices.filter((inv) => {
      if (inv.status !== 'Paid') return false
      const d = new Date(inv.receivedDate)
      return d >= start && d <= end
    })
    weeks.push({
      week: format(start, 'MMM d'),
      amount: paid.reduce((s, i) => s + i.amount, 0),
      count: paid.length,
    })
  }
  return weeks
}

const PIE_COLORS = ['#f59e0b', '#10b981', '#ef4444', '#6c63ff']

export default function Reports() {
  const { data: invoices = [] } = useInvoices()
  const [view, setView] = useState<'week' | 'month'>('week')

  const weeklyData = groupByWeek(invoices)
  const totalPaid = invoices.filter((i) => i.status === 'Paid').reduce((s, i) => s + i.amount, 0)
  const totalApproved = invoices.filter((i) => i.status === 'Approved').reduce((s, i) => s + i.amount, 0)

  const pieData = [
    { name: 'Pending', value: invoices.filter((i) => i.status === 'Pending').length },
    { name: 'Approved', value: invoices.filter((i) => i.status === 'Approved').length },
    { name: 'Rejected', value: invoices.filter((i) => i.status === 'Rejected').length },
    { name: 'Paid', value: invoices.filter((i) => i.status === 'Paid').length },
  ].filter((d) => d.value > 0)

  const paidInvoices = invoices.filter((i) => i.status === 'Paid')

  const exportCSV = () => {
    const header = 'Invoice ID,Sender,Date,Amount,Transaction ID\n'
    const rows = paidInvoices.map((i) =>
      `${i.invoiceId},${i.sender},${i.receivedDate},${i.amount},${i.transactionId || ''}`
    ).join('\n')
    const blob = new Blob([header + rows], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `paid-invoices-${format(new Date(), 'yyyy-MM-dd')}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div>
      <div className="flex-between mb-24">
        <div className="page-header" style={{ marginBottom: 0 }}>
          <h1>Reports</h1>
          <p>Weekly summary — auto-generated by workflow every Friday at 5pm</p>
        </div>
        <button className="btn btn-primary" onClick={exportCSV}>
          ⬇ Export CSV
        </button>
      </div>

      {/* Summary Stat Cards */}
      <div className="grid grid-3 mb-24">
        <div className="card">
          <div className="stat-icon purple">💰</div>
          <div className="card-title">Total Paid</div>
          <div className="card-value" style={{ fontSize: 28 }}>${totalPaid.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
          <div className="card-sub">{paidInvoices.length} invoices completed</div>
        </div>
        <div className="card">
          <div className="stat-icon green">✅</div>
          <div className="card-title">Approved (Pending Payment)</div>
          <div className="card-value" style={{ fontSize: 28 }}>${totalApproved.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
          <div className="card-sub">Awaiting processing</div>
        </div>
        <div className="card">
          <div className="stat-icon amber">📋</div>
          <div className="card-title">Total Invoices</div>
          <div className="card-value" style={{ fontSize: 28 }}>{invoices.length}</div>
          <div className="card-sub">All time</div>
        </div>
      </div>

      <div className="grid grid-2 mb-24">
        {/* Revenue Chart */}
        <div className="card">
          <div className="flex-between mb-16">
            <div className="card-title" style={{ marginBottom: 0 }}>Revenue by Week</div>
            <div className="flex gap-8">
              <button className={view === 'week' ? 'btn btn-primary btn-sm' : 'btn btn-ghost btn-sm'} onClick={() => setView('week')}>Weekly</button>
            </div>
          </div>
          <div className="chart-wrap">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={weeklyData} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="week" tick={{ fontSize: 12, fill: '#8892b0' }} />
                <YAxis tick={{ fontSize: 12, fill: '#8892b0' }} tickFormatter={(v) => `$${v}`} />
                <Tooltip
                  content={({ active, payload, label }) => {
                    if (active && payload && payload.length) {
                      return (
                        <div style={{ background: '#1a1e35', border: '1px solid #252a45', borderRadius: 8, padding: '10px 14px', color: '#e8eaf0', fontSize: 13 }}>
                          <div style={{ marginBottom: 4, color: '#8892b0' }}>{label}</div>
                          <div style={{ fontWeight: 700 }}>${Number(payload[0].value).toLocaleString()}</div>
                        </div>
                      )
                    }
                    return null
                  }}
                />
                <Bar dataKey="amount" radius={[4, 4, 0, 0]}>
                  {weeklyData.map((_, i) => (
                    <Cell key={i} fill={i === weeklyData.length - 1 ? '#6c63ff' : '#3730a3'} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Status Pie */}
        <div className="card">
          <div className="card-title">Invoice Status Breakdown</div>
          <div className="chart-wrap">
            {pieData.length > 0 ? (
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={pieData} cx="50%" cy="45%" outerRadius={90} innerRadius={50} dataKey="value" paddingAngle={3}>
                    {pieData.map((_, i) => (
                      <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />
                    ))}
                  </Pie>
                  <Legend iconType="circle" iconSize={10} formatter={(v) => <span style={{ color: '#8892b0', fontSize: 12 }}>{v}</span>} />
                  <Tooltip contentStyle={{ background: '#1a1e35', border: '1px solid #252a45', borderRadius: 8 }} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="empty-state"><p>No data available</p></div>
            )}
          </div>
        </div>
      </div>

      {/* Paid Invoices Table */}
      <div className="card" style={{ padding: 0 }}>
        <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border-color)' }}>
          <div className="card-title" style={{ marginBottom: 0 }}>Paid Invoices</div>
        </div>
        <div className="table-wrap">
          <table className="table">
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Sender</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Transaction ID</th>
              </tr>
            </thead>
            <tbody>
              {paidInvoices.length > 0 ? paidInvoices.map((inv) => (
                <tr key={inv.invoiceId}>
                  <td className="font-semibold text-accent">{inv.invoiceId}</td>
                  <td className="text-sm">{inv.sender}</td>
                  <td className="text-sm text-muted">{inv.receivedDate}</td>
                  <td className="font-semibold">${inv.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                  <td className="text-xs text-muted" style={{ fontFamily: 'monospace' }}>{inv.transactionId || '—'}</td>
                </tr>
              )) : (
                <tr><td colSpan={5} className="table-empty">No paid invoices yet.</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
